### ISSUE TITLE
Enable running DPS with flow-go localnet

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-dps#5]
We need a convenient way to run DPS with a localnet cluster to do manual testing locally with smaller datasets. This is an Epic to track the work required to get that working.

The goal is to enable fast and efficient iterative development on DPS and flow nodes. The end result should enable a developer to make changes to local DPS and flow nodes, quickly refresh the localnet environment and run manual tests

**Comment by franklywatson** [comment]
Switching sub tasks to different epic
